#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;

extern void _ampain_reg(void);
extern void _ampa_reg(void);
extern void _cadynin_reg(void);
extern void _cadyn_reg(void);
extern void _calcb_reg(void);
extern void _calc_reg(void);
extern void _cal_reg(void);
extern void _cancr_reg(void);
extern void _canin_reg(void);
extern void _can_reg(void);
extern void _car_reg(void);
extern void _catcb_reg(void);
extern void _cat_reg(void);
extern void _cpampain_reg(void);
extern void _gabaain_reg(void);
extern void _gabaa_reg(void);
extern void _gabab_reg(void);
extern void _hcb_reg(void);
extern void _hin_reg(void);
extern void _h_reg(void);
extern void _ican_reg(void);
extern void _iccb_reg(void);
extern void _iccr_reg(void);
extern void _icin_reg(void);
extern void _ikscb_reg(void);
extern void _ikscr_reg(void);
extern void _iksin_reg(void);
extern void _iks_reg(void);
extern void _kadistcr_reg(void);
extern void _kadistin_reg(void);
extern void _kadist_reg(void);
extern void _kaproxcb_reg(void);
extern void _kaproxin_reg(void);
extern void _kaprox_reg(void);
extern void _kcain_reg(void);
extern void _kca_reg(void);
extern void _kctin_reg(void);
extern void _kct_reg(void);
extern void _kdrcb_reg(void);
extern void _kdrcr_reg(void);
extern void _kdrin_reg(void);
extern void _kdr_reg(void);
extern void _nafcb_reg(void);
extern void _nafcr_reg(void);
extern void _nafin_reg(void);
extern void _naf_reg(void);
extern void _nafx_reg(void);
extern void _nap_reg(void);
extern void _netstim_reg(void);
extern void _NMDAIN_reg(void);
extern void _NMDA_reg(void);
extern void _sinclamp_reg(void);
extern void _vecstim_reg(void);

void modl_reg(){
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");

    fprintf(stderr," ampain.mod");
    fprintf(stderr," ampa.mod");
    fprintf(stderr," cadynin.mod");
    fprintf(stderr," cadyn.mod");
    fprintf(stderr," calcb.mod");
    fprintf(stderr," calc.mod");
    fprintf(stderr," cal.mod");
    fprintf(stderr," cancr.mod");
    fprintf(stderr," canin.mod");
    fprintf(stderr," can.mod");
    fprintf(stderr," car.mod");
    fprintf(stderr," catcb.mod");
    fprintf(stderr," cat.mod");
    fprintf(stderr," cpampain.mod");
    fprintf(stderr," gabaain.mod");
    fprintf(stderr," gabaa.mod");
    fprintf(stderr," gabab.mod");
    fprintf(stderr," hcb.mod");
    fprintf(stderr," hin.mod");
    fprintf(stderr," h.mod");
    fprintf(stderr," ican.mod");
    fprintf(stderr," iccb.mod");
    fprintf(stderr," iccr.mod");
    fprintf(stderr," icin.mod");
    fprintf(stderr," ikscb.mod");
    fprintf(stderr," ikscr.mod");
    fprintf(stderr," iksin.mod");
    fprintf(stderr," iks.mod");
    fprintf(stderr," kadistcr.mod");
    fprintf(stderr," kadistin.mod");
    fprintf(stderr," kadist.mod");
    fprintf(stderr," kaproxcb.mod");
    fprintf(stderr," kaproxin.mod");
    fprintf(stderr," kaprox.mod");
    fprintf(stderr," kcain.mod");
    fprintf(stderr," kca.mod");
    fprintf(stderr," kctin.mod");
    fprintf(stderr," kct.mod");
    fprintf(stderr," kdrcb.mod");
    fprintf(stderr," kdrcr.mod");
    fprintf(stderr," kdrin.mod");
    fprintf(stderr," kdr.mod");
    fprintf(stderr," nafcb.mod");
    fprintf(stderr," nafcr.mod");
    fprintf(stderr," nafin.mod");
    fprintf(stderr," naf.mod");
    fprintf(stderr," nafx.mod");
    fprintf(stderr," nap.mod");
    fprintf(stderr," netstim.mod");
    fprintf(stderr," NMDAIN.mod");
    fprintf(stderr," NMDA.mod");
    fprintf(stderr," sinclamp.mod");
    fprintf(stderr," vecstim.mod");
    fprintf(stderr, "\n");
  }
  _ampain_reg();
  _ampa_reg();
  _cadynin_reg();
  _cadyn_reg();
  _calcb_reg();
  _calc_reg();
  _cal_reg();
  _cancr_reg();
  _canin_reg();
  _can_reg();
  _car_reg();
  _catcb_reg();
  _cat_reg();
  _cpampain_reg();
  _gabaain_reg();
  _gabaa_reg();
  _gabab_reg();
  _hcb_reg();
  _hin_reg();
  _h_reg();
  _ican_reg();
  _iccb_reg();
  _iccr_reg();
  _icin_reg();
  _ikscb_reg();
  _ikscr_reg();
  _iksin_reg();
  _iks_reg();
  _kadistcr_reg();
  _kadistin_reg();
  _kadist_reg();
  _kaproxcb_reg();
  _kaproxin_reg();
  _kaprox_reg();
  _kcain_reg();
  _kca_reg();
  _kctin_reg();
  _kct_reg();
  _kdrcb_reg();
  _kdrcr_reg();
  _kdrin_reg();
  _kdr_reg();
  _nafcb_reg();
  _nafcr_reg();
  _nafin_reg();
  _naf_reg();
  _nafx_reg();
  _nap_reg();
  _netstim_reg();
  _NMDAIN_reg();
  _NMDA_reg();
  _sinclamp_reg();
  _vecstim_reg();
}
