#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/cluster/applications/neuron_np/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/cluster/applications/neuron_np/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/cluster/aleka/MainPath/Desktop/FSBC_model/Multicompartmental_Biophysical_models/mechanism/x86_64/.libs/libnrnmech.so" "$@"
